package curl

import (
	"bufio"
	"net/http"
	"net/url"
	"os"
	"strings"
)

// cookieJar is a minimal jar that:
//   - accepts inline cookie pairs from -b,
//   - reads/writes Netscape cookies.txt format from -b file / -c file,
//   - is shared across redirects in the same invocation.
type cookieJar struct {
	cookies []http.Cookie
}

func newCookieJar() *cookieJar { return &cookieJar{} }

// LoadInput accepts either inline pairs ("k=v; k2=v2") or a file path.
func (j *cookieJar) LoadInput(input string) error {
	if looksLikeCookieFile(input) {
		return j.LoadFile(input)
	}
	parts := strings.Split(input, ";")
	for _, p := range parts {
		p = strings.TrimSpace(p)
		eq := strings.IndexByte(p, '=')
		if eq < 0 {
			continue
		}
		j.cookies = append(j.cookies, http.Cookie{Name: p[:eq], Value: p[eq+1:]})
	}
	return nil
}

// LoadFile reads a Netscape-format cookies.txt.
func (j *cookieJar) LoadFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) < 7 {
			continue
		}
		j.cookies = append(j.cookies, http.Cookie{
			Domain: fields[0],
			Path:   fields[2],
			Secure: strings.EqualFold(fields[3], "TRUE"),
			Name:   fields[5],
			Value:  fields[6],
		})
	}
	return sc.Err()
}

// HeaderFor returns the Cookie header value for the given URL, or "".
func (j *cookieJar) HeaderFor(u *url.URL) string {
	if u == nil {
		return ""
	}
	var ps []string
	for _, c := range j.cookies {
		if !cookieMatches(c, u) {
			continue
		}
		ps = append(ps, c.Name+"="+c.Value)
	}
	return strings.Join(ps, "; ")
}

// StoreFromResponse merges Set-Cookie headers from resp into the jar.
func (j *cookieJar) StoreFromResponse(resp *http.Response) {
	for _, c := range resp.Cookies() {
		if c.Domain == "" {
			c.Domain = resp.Request.URL.Hostname()
		}
		if c.Path == "" {
			c.Path = "/"
		}
		j.replaceOrAppend(*c)
	}
}

func (j *cookieJar) replaceOrAppend(c http.Cookie) {
	for i, existing := range j.cookies {
		if existing.Name == c.Name && existing.Domain == c.Domain && existing.Path == c.Path {
			j.cookies[i] = c
			return
		}
	}
	j.cookies = append(j.cookies, c)
}

// SaveJar writes the jar in Netscape format to path.
func (j *cookieJar) SaveJar(path string) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	bw := bufio.NewWriter(f)
	defer bw.Flush()
	bw.WriteString("# Netscape HTTP Cookie File\n")
	bw.WriteString("# https://curl.se/docs/http-cookies.html\n")
	bw.WriteString("# This file was generated by bag curl.\n\n")
	for _, c := range j.cookies {
		bw.WriteString(strings.Join([]string{
			c.Domain,
			boolStr(strings.HasPrefix(c.Domain, ".")),
			emptyDefault(c.Path, "/"),
			boolStr(c.Secure),
			"0",
			c.Name,
			c.Value,
		}, "\t"))
		bw.WriteByte('\n')
	}
	return nil
}

func boolStr(b bool) string {
	if b {
		return "TRUE"
	}
	return "FALSE"
}

func emptyDefault(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

func cookieMatches(c http.Cookie, u *url.URL) bool {
	host := u.Hostname()
	if c.Domain != "" {
		d := strings.TrimPrefix(c.Domain, ".")
		if !(host == d || strings.HasSuffix(host, "."+d)) {
			return false
		}
	}
	path := u.Path
	if path == "" {
		path = "/"
	}
	cp := c.Path
	if cp == "" {
		cp = "/"
	}
	if !strings.HasPrefix(path, cp) {
		return false
	}
	if c.Secure && u.Scheme != "https" {
		return false
	}
	return true
}
